export const projects = [
  {
    title: 'GPT3 Landing Page',
    description: "A project On GPT3 Landing Page is a awesome page Landing Web Page. Our attention to detail will connect experience working with global, national, and regional brands we understand the experience of eating goes beyond taste buds. Our attention to detail will connect form and durability to enhance the experience",
      image: '/images/GPT3.PNG',
      tags: ['React  UI/UX Figma', 'file and folder structure','Styled Components','CSS'],
    source: 'https://github.com/jamiltarek55/UI-UX_GPT3_Landing_Page',
    visit: 'https://frabjous-peony-2e66c9.netlify.app/',
    id: 0,
  },
  {
    title: 'Modern Restaurant',
    description: "GERICHT is a deep connection with the restaurant industry. With experience working with global, national, and regional brands we understand the experience of eating goes beyond taste buds.  The space must meet the expectation of the brand and food.  Our attention to detail will connect form, function, and durability to enhance the experience.",
      image: '/images/Gericht.PNG',
      tags: ['React UI/UX', 'file and folder structure','Styled Components','CSS'],
    source: 'https://github.com/jamiltarek55/Modern_UI_UX_Restaurant',
    visit: 'https://thunderous-gnome-cb2663.netlify.app/',
    id: 1,
  },
  {
    title: 'Real Estate Web',
    description: "Tarek's RealTor is the most professional Real Estate Agency in Bangladesh. It has been doing Property BUY, SALE, RENT, RENAL MANAGEMENT & PROVIDING property DOCUMENTATION SERVICE like SALE PERMISSION, REGISTRATION.",
      image: '/images/FrontPage.PNG',
      tags: ['React Next', 'file and folder structure ',' Chakra UI Bayut Api'],
    source: 'https://github.com/jamiltarek55/Next-RealTor',
    visit: 'https://next-real-tor.vercel.app/',
    id: 2,
  },
  {
    title: 'React Pizza Shop',
    description: " SHEY PIZZA is a US based international restaurant chain that is home to one of the world’s favorite Pizzas and much more. The brand had started their journey Bangladesh. when I Developed my first pizza restaurant app Using React",
      image: '/images/Shey.PNG',
      tags: ['React', 'CSS','Bootstrap'],
    source: 'https://github.com/jamiltarek55/React-Pizza-Shop',
    visit: 'https://ornate-torte-2f5b32.netlify.app/',
    id: 3,
  },
  {
    title: 'StartUp Landing Page',
    description: "A project on Startup Landing is a Next landing page template for mobile apps, books, any single product or even webinar, and many more. It is a carefully designed template that can effortlessly take whatever visage you think best suits for business needs.",
      image: '/images/StartUp.PNG',
      tags: ['React Next', 'Theme UI','Framer Motion & More'],
    source: 'https://github.com/jamiltarek55/agency-landing-page',
    visit: 'https://agency-landing-page-coral.vercel.app/',
    id: 4,
  },
  {
    title: 'React Google Clone',
    description: "A fully functional replica of Google's main page, you can use it for searches and everything else. Styled with TailWindCSS to look as close as possible to current google main page using react context api and google search api and more, a bit of jquery magic to make it fully functional.",
      image: '/images/Google.PNG',
      tags: ['React', 'Context-api','TailWindCSS','Google API'],
    source: 'https://github.com/jamiltarek55/React-google-Clone',
    visit: 'https://prismatic-kangaroo-9f53dd.netlify.app/search',
    id: 5,
  },
  {
    title: 'RAINY BRAIN',
    description: "A project on predicting whether it will rain tomorrow or not by using the Rainfall in Australia dataset This project is tested over lot of ml models like catboost, xgboost, random forest, support vector classifier, etc.. Out of these models catboost performed very well giving an AUC score around and ROC score of 88.",
      image: '/images/1.png',
      tags: ['Machine Learning', 'Python','Flask'],
    source: 'https://github.com/jamiltarek55/Rainy-Brain',
    visit: 'https://rainfallbr.herokuapp.com/',
    id: 6,
  },
  {
    title: 'FLIGHT PRICE',
    description:"This Project is used to predict the flight prices. This dataset consists of 10683 records with 11 columns that explain about the flight in India by some Indian and foreign Airlines in 2019.The Data Science Life Cycle to process the data such as Cleaning dataset, feature engineering, splitting dataset feature selection, and hyperparameter tuning.",
    image: '/images/2.png',
    tags: ['Machine Learning', 'Python','Flask'],
    source: 'https://github.com/jamiltarek55/FlightPricePrediction',
    visit: 'https://flightpricepredforme.herokuapp.com/',
    id: 7,
  },
  {
    title: 'Car PRICE',
    description: "This Project is used to predict the  used car prices. This dataset consists of 10683 records with 11 columns that explain about the flight in India by some Indian and foreign Airlines in 2019.The Data Science Life Cycle to process the data such as Cleaning dataset, feature engineering, splitting dataset feature selection, and hyperparameter tuning.",
      image: '/images/3.jpg',
      tags: ['Machine Learning', 'Python','Flask'],
    source: 'https://github.com/jamiltarek55/CarPricePrediction',
    visit: 'https://cpfme.herokuapp.com/',
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2021, text: 'Started my journey', },
  { year: 2021, text: 'Develop Some Frontend And Full-Stack JavaScript Projects using React, Next & MERN', },
  { year: 2021, text: ' develop different Machine Learning Projects Using Python,', },
  { year: 2022, text: 'Searching To Get Full Time Professional Job ', },
  { year: 2023, text: 'Will go On', },
];